# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:23-jdk

# Set the working directory in the container
WORKDIR /app

# Copy the WAR file into the container at /app/application.war
COPY hkjc-lm-frontend-manual-1.1.1.war /app/hkjc-lm-frontend-manual.war

# Expose the port that the application will run on
EXPOSE 24680

# Add the Datadog Java Agent
ADD dd-java-agent.jar /app/dd-java-agent.jar

ADD opentelemetry-javaagent.jar /app/opentelemetry-javaagent.jar

# # Define environment variables for Datadog configuration
# ENV DD_SERVICE=otel-testing-app
# ENV DD_ENV=staging
# ENV DD_VERSION=0.1

# Set the entry point to run the WAR file
# ENTRYPOINT ["java", "-javaagent:/app/dd-java-agent.jar", "-Ddd.profiling.enabled=true", "-XX:FlightRecorderOptions=stackdepth=256", "-Ddd.logs.injection=true", "-Ddd.service=hkjc-otel-poc", "-Ddd.env=staging", "-Ddd.version=1.0", "-jar", "/app/demo-0.0.1-SNAPSHOT.war"]